const heroConfigs = [
    {
        "faction": "horde",
        "heroName": "Aethas Sunreaver",
        "heroTitle": "Archmage",
        "heroQuote": "\"We must overcome the mistakes of the past.\"",
        "heroImageUrl": "img/aethas-sunreaver.jpg",
        "heroImagePosition": "1px -52px",
        "heroImageSize": "100%",
        "health": 7,
        "startingLocation": "DALARAN",
        "startingZone": "green",
        "power1Name": "Fireball",
        "power1DescPrefix": "Free Action: ",
        "power1DescSuffix": "Remove 1 ghoul from your space. Limit once per turn.",
        "power2Name": "Blink",
        "power2DescPrefix": "Free Action: ",
        "power2DescSuffix": "Move to a connected space. Limit once per turn.",
        "collection": "Kirin Tor",
    },
    {
        "faction": "kirin-tor",
        "heroName": "Alard Schmied",
        "heroTitle": "Grand Master Blacksmithing Trainer",
        "heroQuote": "\"Don't you just love the smell of hot steel in the morning?\"",
        "heroImageUrl": "img/alard-schmied.jpg",
        "heroImagePosition": "0px -43px",
        "heroImageSize": "100%",
        "health": 6,
        "startingLocation": "DALARAN",
        "startingZone": "green",
        "power1Name": "Blacksmith",
        "power1DescPrefix": "",
        "power1DescSuffix": "All heroes in your region have +🛡️ when they fight or quest.",
        "power2Name": "Civilian",
        "power2DescPrefix": "",
        "power2DescSuffix": "Cancel 1 rolled ✊🏼 when you fight.",
        "collection": "Kirin Tor",
        "shortName": "Armorer",
    },
    {
        "faction": "wyrmrest",
        "heroName": "Alexstrasza",
        "heroTitle": "The Life-Binder",
        "heroQuote": "\"Life itself is with you.\"",
        "heroImageUrl": "img/alexstrasza.png",
        "heroImagePosition": "-5px -24px",
        "heroImageSize": "104%",
        "health": 8,
        "startingLocation": "WYRMREST TEMPLE",
        "startingZone": "purple",
        "power1Name": "Gift of Life",
        "power1DescPrefix": "Action: ",
        "power1DescSuffix": "One hero in your region heals 3, and you suffer 1 damage. Limit once per turn.",
        "power2Name": "Flame Buffet",
        "power2DescPrefix": "Free Action: ",
        "power2DescSuffix": "Remove 1 ghoul from your space and move up to 1 enemy to a connected space. Limit once per turn.",
        "collection": "Wyrmrest Accord",
    },
    {
        "faction": "argent",
        "heroName": "Aliocha Segard",
        "heroTitle": "Argent Crusade Quartermaster",
        "heroQuote": "\"Wear the tabard of the Argent Crusade with pride and honor!\"",
        "heroImageUrl": "img/aliocha-segard.jpg",
        "heroImagePosition": "0px 0px",
        "heroImageSize": "108%",
        "health": 7,
        "startingLocation": "ARGENT TOURNAMENT",
        "startingZone": "green",
        "power1Name": "Veteran Crusader",
        "power1DescPrefix": "",
        "power1DescSuffix": "Ignore all damage during the  'Activate Abomination' step.",
        "power2Name": "Quartermaster",
        "power2DescPrefix": "",
        "power2DescSuffix": "Your hand limit is 8 cards.",
        "collection": "Argent Crusade",
    },
    {
        "faction": "alliance",
        "heroName": "Anduin Wrynn",
        "heroTitle": "Crown Prince of Stormwind",
        "heroQuote": "\"Each life, a universe.\"",
        "heroImageUrl": "img/anduin-wrynn.jpg",
        "heroImagePosition": "0px -76px",
        "heroImageSize": "100%",
        "health": 6,
        "startingLocation": "VALGARDE",
        "startingZone": "purple",
        "power1Name": "Holy Smite",
        "power1DescPrefix": "Free Action: ",
        "power1DescSuffix": "Remove 1 ghoul from your space. Limit once per turn.",
        "power2Name": "Flash Heal",
        "power2DescPrefix": "Free Action: ",
        "power2DescSuffix": "1 hero on your space heals 1. Limit once per turn.",
        "collection": "Mainland Reinforcements",
    },
    {
        "faction": "kirin-tor",
        "heroName": "Archivist Elysiana",
        "heroTitle": "Curator",
        "heroQuote": "\"Just another organizational challenge.\"",
        "heroImageUrl": "img/archivist-elysiana.jpg",
        "heroImagePosition": "0px 0px",
        "heroImageSize": "100%",
        "health": 7,
        "startingLocation": "DALARAN",
        "startingZone": "green",
        "power1Name": "Discover",
        "power1DescPrefix": "Action: ",
        "power1DescSuffix": "Draw 1 hero card. Limit once per turn.",
        "power2Name": "Curate",
        "power2DescPrefix": "Action: ",
        "power2DescSuffix": "Peek and rearrange as you wish the top 3 cards of the hero deck. Limit once per turn.",
        "collection": "Kirin Tor",
    },
    {
        "faction": "alliance",
        "heroName": "Bolvar Fordragon",
        "heroTitle": "Highlord",
        "heroQuote": "\"I don't know what awaits us.\"",
        "heroImageUrl": "img/bolvar-fordragon.jpg",
        "heroImagePosition": "0px -32px",
        "heroImageSize": "100%",
        "health": 7,
        "startingLocation": "VALIANCE KEEP",
        "startingZone": "red",
        "power1Name": "Crusader Strike",
        "power1DescPrefix": "Action: ",
        "power1DescSuffix": "Remove up to 2 ghouls from your space. Limit once per turn.",
        "power2Name": "Fordragon's Resolve",
        "power2DescPrefix": "",
        "power2DescSuffix": "Heroes on your space have +🛡️ when they fight.",
        "collection": "The Wrathgate",
    },
    {
        "faction": "explorers",
        "heroName": "Brann Bronzebeard",
        "heroTitle": "Leader of the Explorers' League",
        "heroQuote": "\"The answers are here, I can feel it.\"",
        "heroImageUrl": "img/brann-bronzebeard.png",
        "heroImagePosition": "-10px -4px",
        "heroImageSize": "104%",
        "health": 6,
        "startingLocation": "TEMPLE OF STORMS",
        "startingZone": "green",
        "power1Name": "Survey",
        "power1DescPrefix": "Action: ",
        "power1DescSuffix": "+✊🏼 on your next quest action this turn. Limit once per turn.",
        "power2Name": "Historian",
        "power2DescPrefix": "",
        "power2DescSuffix": "When you quest, you may contribute the top card of the hero discard as if it were in your hand.",
        "collection": "Explorers & Hunters",
    },
    {
        "faction": "alliance",
        "heroName": "Broll Bearmantle",
        "heroTitle": "Champion of the Crimson Ring",
        "heroQuote": "\"We fight as we are.\"",
        "heroImageUrl": "img/broll-bearmantle.jpg",
        "heroImagePosition": "-2px -20px",
        "heroImageSize": "100%",
        "health": 7,
        "startingLocation": "Grizzlemaw",
        "startingZone": "purple",
        "power1Name": "Swipe",
        "power1DescPrefix": "Free Action: ",
        "power1DescSuffix": "Remove up to 2 ghouls from your space. Limit once per turn.",
        "power2Name": "Mangle",
        "power2DescPrefix": "Free Action: ",
        "power2DescSuffix": "Remove 1 ghoul from your space. Limit once per turn.",
        "collection": "Mainland Reinforcements",
    },
    {
        "faction": "horde",
        "heroName": "Cairne Bloodhoof",
        "heroTitle": "High Chieftain",
        "heroQuote": "\"For honor!\"",
        "heroImageUrl": "img/cairne-bloodhoof.jpg",
        "heroImagePosition": "-1px -33px",
        "heroImageSize": "100%",
        "health": 7,
        "startingLocation": "WARSONG HOLD",
        "startingZone": "red",
        "power1Name": "Thunderclap",
        "power1DescPrefix": "Action: ",
        "power1DescSuffix": "Remove up to 2 ghouls from your space and move up to 1 ghoul to a connected space. Limit once per turn.",
        "power2Name": "Bloodhoof Runespear",
        "power2DescPrefix": "",
        "power2DescSuffix": "When you fight, treat all 🛡️ as ✊🏼.",
        "collection": "Mainland Reinforcements",
    },
    {
        "faction": "kirin-tor",
        "heroName": "Charles Worth",
        "heroTitle": "Grand Master Tailoring Trainer",
        "heroQuote": "\"Good day to you!\"",
        "heroImageUrl": "img/charles-worth.jpg",
        "heroImagePosition": "0px -36px",
        "heroImageSize": "100%",
        "health": 6,
        "startingLocation": "DALARAN",
        "startingZone": "green",
        "power1Name": "Tailor",
        "power1DescPrefix": "",
        "power1DescSuffix": "All heroes in your region have +🛡️ when they fight or quest.",
        "power2Name": "Civilian",
        "power2DescPrefix": "",
        "power2DescSuffix": "Cancel 1 rolled ✊🏼 when you fight.",
        "collection": "Kirin Tor",
        "shortName": "Armorer",
    },
    {
        "faction": "wyrmrest",
        "heroName": "Chromie",
        "heroTitle": "Ambassador of the Bronze Dragonflight",
        "heroQuote": "\"Is this the first time we've met?\"",
        "heroImageUrl": "img/chromie.jpg",
        "heroImagePosition": "-2px -20px",
        "heroImageSize": "100%",
        "health": 8,
        "startingLocation": "WYRMREST TEMPLE",
        "startingZone": "purple",
        "power1Name": "Rewind",
        "power1DescPrefix": "Action: ",
        "power1DescSuffix": "Move the top card from the hero discard into your hand. Limit once per turn.",
        "power2Name": "See the Future",
        "power2DescPrefix": "Free Action: ",
        "power2DescSuffix": "Peek at the top card of the Scourge deck.",
        "collection": "Wyrmrest Accord",
    },
    {
        "faction": "argent",
        "heroName": "Dalfors",
        "heroTitle": "Crusader Lord",
        "heroQuote": "\"Let 'em come. They'll pay for what they've done!\"",
        "heroImageUrl": "img/dalfors.jpg",
        "heroImagePosition": "0px 0px",
        "heroImageSize": "116%",
        "health": 6,
        "startingLocation": "THE BREACH",
        "startingZone": "green",
        "power1Name": "Exorcism",
        "power1DescPrefix": "Action: ",
        "power1DescSuffix": "Remove 1 abomination from your space. Limit once per turn.",
        "power2Name": "Consecration",
        "power2DescPrefix": "Free Action: ",
        "power2DescSuffix": "Remove all ghouls from your space. Limit once per turn.",
        "collection": "Argent Crusade",
    },
    {
        "faction": "ebon-blade",
        "heroName": "Darion Mograine",
        "heroTitle": "Leader of The Knights of the Ebon Blade",
        "heroQuote": "\"The Knights of the Ebon Blade will not falter.\"",
        "heroImageUrl": "img/darion-mograine.png",
        "heroImagePosition": "-81px -2px",
        "heroImageSize": "156%",
        "health": 7,
        "startingLocation": "SHADOW VAULT",
        "startingZone": "green",
        "power1Name": "Dark Command",
        "power1DescPrefix": "Free Action: ",
        "power1DescSuffix": "Roll 1 die, remove 1 ghoul on your space for each rolled ✊🏼. Limit once per turn.",
        "power2Name": "Corpse Explosion",
        "power2DescPrefix": "",
        "power2DescSuffix": "For every 2 enemies that die on your space during your actions, deal 1 damage among enemies on connected spaces.",
        "collection": "Ebon Blade",
    },
    {
        "faction": "kirin-tor",
        "heroName": "Diane Cannings",
        "heroTitle": "Grand Master Leatherworking Trainer",
        "heroQuote": "\"Flexibility in your armor plays a crucial part.\"",
        "heroImageUrl": "img/diane-cannings.jpg",
        "heroImagePosition": "0px 0px",
        "heroImageSize": "112%",
        "health": 6,
        "startingLocation": "DALARAN",
        "startingZone": "green",
        "power1Name": "Leatherworker",
        "power1DescPrefix": "",
        "power1DescSuffix": "All heroes in your region have +🛡️ when they fight or quest.",
        "power2Name": "Civilian",
        "power2DescPrefix": "",
        "power2DescSuffix": "Cancel 1 rolled ✊🏼 when you fight.",
        "collection": "Kirin Tor",
        "shortName": "Armorer",
    },
    {
        "faction": "horde",
        "heroName": "Dranosh Saurfang",
        "heroTitle": "Commander of the Kor'kron Vanguard",
        "heroQuote": "\"Blood and glory await us!\"",
        "heroImageUrl": "img/dranosh-saurfang.png",
        "heroImagePosition": "-26px 0px",
        "heroImageSize": "112%",
        "health": 6,
        "startingLocation": "THE WRATHGATE",
        "startingZone": "red",
        "power1Name": "Charge",
        "power1DescPrefix": "Action: ",
        "power1DescSuffix": "Move to a connected space and fight on that space. Limit once per turn.",
        "power2Name": "Enrage",
        "power2DescPrefix": "",
        "power2DescSuffix": "+✊🏼 when you fight if you have 4 health or less.",
        "collection": "The Wrathgate",
    },
    {
        "faction": "argent",
        "heroName": "Eadric the Pure",
        "heroTitle": "Grand Champion of the Argent Crusade",
        "heroQuote": "\"We must all be strong in the presence of the Scourge.\"",
        "heroImageUrl": "img/eadric-the-pure.jpg",
        "heroImagePosition": "1px -58px",
        "heroImageSize": "100%",
        "health": 7,
        "startingLocation": "ARGENT TOURNAMENT",
        "startingZone": "green",
        "power1Name": "Holy Light",
        "power1DescPrefix": "Free Action: ",
        "power1DescSuffix": "Another hero on your space heals 1 or remove 1 ghoul from your space. Limit once per turn.",
        "power2Name": "Divine Shield",
        "power2DescPrefix": "Free Action: ",
        "power2DescSuffix": "You take no damage during your next action this turn. Limit once per turn.",
        "collection": "Argent Crusade",
    },
    {
        "faction": "horde",
        "heroName": "Elite Tauren Chieftain",
        "heroTitle": "Rock God",
        "heroQuote": "\"I am Murloc!\"",
        "heroImageUrl": "img/elite-tauren-chieftain.jpg",
        "heroImagePosition": "-87px -2px",
        "heroImageSize": "140%",
        "health": 7,
        "startingLocation": "The Nexus",
        "startingZone": "red",
        "power1Name": "Mosh Pit",
        "power1DescPrefix": "Free Action: ",
        "power1DescSuffix": "Remove up to 2 ghouls from your space. Heroes on your space suffer 1 damage each. Limit once per turn.",
        "power2Name": "Pumped Up!",
        "power2DescPrefix": "",
        "power2DescSuffix": "Heroes on your space have +🛡️ when they quest.",
        "collection": "Mainland Reinforcements",
    },
    {
        "faction": "argent",
        "heroName": "Entari",
        "heroTitle": "Crusade Commander",
        "heroQuote": "\"The Argent Crusade succeeded.\"",
        "heroImageUrl": "img/entari.jpg",
        "heroImagePosition": "0px 0px",
        "heroImageSize": "108%",
        "health": 7,
        "startingLocation": "The Breach",
        "startingZone": "green",
        "power1Name": "Avenger's Shield",
        "power1DescPrefix": "Free Action: ",
        "power1DescSuffix": "Remove up to 2 ghouls from your space. Limit once per turn.",
        "power2Name": "Avenge",
        "power2DescPrefix": "",
        "power2DescSuffix": "After you suffer damage, remove 1 ghoul from your space.",
        "collection": "Argent Crusade",
    },
    {
        "faction": "argent",
        "heroName": "Falstaav",
        "heroTitle": "Commander ",
        "heroQuote": "\"Dispatch the Scourge with all the zeal you can muster!\"",
        "heroImageUrl": "img/falstaav.jpg",
        "heroImagePosition": "0px 0px",
        "heroImageSize": "116%",
        "health": 7,
        "startingLocation": "KOLRAMAS",
        "startingZone": "purple",
        "power1Name": "Retribution",
        "power1DescPrefix": "Free Action: ",
        "power1DescSuffix": "Discard 1 hero card and fight in your space.",
        "power2Name": "Devotion Aura",
        "power2DescPrefix": "",
        "power2DescSuffix": "Heroes on your space and connected spaces have +🛡️ when they fight.",
        "collection": "Argent Crusade",
    },
    {
        "faction": "argent",
        "heroName": "Father Gustav",
        "heroTitle": "",
        "heroQuote": "\"The path of the righteous is beset by inequity and evil.\"",
        "heroImageUrl": "img/father-gustav.jpg",
        "heroImagePosition": "0px 0px",
        "heroImageSize": "100%",
        "health": 6,
        "startingLocation": "The Breach",
        "startingZone": "green",
        "power1Name": "Heal",
        "power1DescPrefix": "Action: ",
        "power1DescSuffix": "1 hero on your space heals 3. Limit once per turn.",
        "power2Name": "Inner Fire",
        "power2DescPrefix": "",
        "power2DescSuffix": "Other heroes on your space have +✊🏼 when they fight.",
        "collection": "Argent Crusade",
    },
    {
        "faction": "argent",
        "heroName": "Father Kamaros",
        "heroTitle": "",
        "heroQuote": "\"Fight the Scourge with all the strength you can muster.\"",
        "heroImageUrl": "img/father-kamaros.jpg",
        "heroImagePosition": "0px 0px",
        "heroImageSize": "100%",
        "health": 6,
        "startingLocation": "The Avalanche",
        "startingZone": "green",
        "power1Name": "Benediction",
        "power1DescPrefix": "Free Action: ",
        "power1DescSuffix": "1 hero on your space heals 1. Limit once per turn.",
        "power2Name": "Power Word: Fortitude",
        "power2DescPrefix": "Free Action: ",
        "power2DescSuffix": "Each hero on your space heals 1. Limit once per turn.",
        "collection": "Argent Crusade",
    },
    {
        "faction": "hs",
        "heroName": "Freya",
        "heroTitle": "Keeper",
        "heroQuote": "\"I can see clearly once more.\"",
        "heroImageUrl": "img/freya.jpg",
        "heroImagePosition": "-4px -2px",
        "heroImageSize": "108%",
        "health": 8,
        "startingLocation": "ULDUAR",
        "startingZone": "green",
        "power1Name": "Touch of Eonar",
        "power1DescPrefix": "Action: ",
        "power1DescSuffix": "One hero in your region heals 2. Limit once per turn.",
        "power2Name": "Attuned to Nature",
        "power2DescPrefix": "",
        "power2DescSuffix": "Heroes in your region have +✊🏼 when they rest.",
        "collection": "Keepers of Ulduar",
    },
    {
        "faction": "horde",
        "heroName": "Garrosh Hellscream",
        "heroTitle": "Overlord of the Warsong Offensive",
        "heroQuote": "\"Show them no mercy.\"",
        "heroImageUrl": "img/garrosh-hellscream.jpg",
        "heroImagePosition": "-5px -12px",
        "heroImageSize": "104%",
        "health": 6,
        "startingLocation": "WARSONG HOLD",
        "startingZone": "red",
        "power1Name": "Bloodthirst",
        "power1DescPrefix": "Free Action: ",
        "power1DescSuffix": "Remove 1 ghoul from your space and heal 1. Limit once per turn.",
        "power2Name": "Armor Up",
        "power2DescPrefix": "",
        "power2DescSuffix": "+🛡️ for each 2 missing health points when you fight or quest.",
        "collection": "Others",
    },
    {
        "faction": "alliance",
        "heroName": "Gelbin Mekkatorque",
        "heroTitle": "King of Gnomes",
        "heroQuote": "\"Pick on someone your own size!\"",
        "heroImageUrl": "img/gelbin-mekkatorque.jpg",
        "heroImagePosition": "0px -5px",
        "heroImageSize": "100%",
        "health": 6,
        "startingLocation": "VALIANCE KEEP",
        "startingZone": "red",
        "power1Name": "Spare Parts",
        "power1DescPrefix": "Action: ",
        "power1DescSuffix": 'Discard a "Fight" card and remove 1 ghoul from your space and each of 3 connected spaces, or discard a "Defend" card and heal 3.',
        "power2Name": "Super Shrink Ray",
        "power2DescPrefix": "Action: ",
        "power2DescSuffix": "Remove 1 abomination from your space and spawn 1 ghoul. Limit once per turn.",
        "collection": "Mainland Reinforcements",
    },
    {
        "faction": "horde",
        "heroName": "Gorth",
        "heroTitle": "Sergeant",
        "heroQuote": "\"Gorth no care if he die! Gorth get put back together!\"",
        "heroImageUrl": "img/hollow-abomination.jpg",
        "heroImagePosition": "-1px -54px",
        "heroImageSize": "cover",
        "health": 7,
        "startingLocation": "VENGEANCE LANDING",
        "startingZone": "purple",
        "power1Name": "Cannibalize",
        "power1DescPrefix": "Action: ",
        "power1DescSuffix": "Remove exactly 1 ghoul from your space and heal 2. Limit once per turn.",
        "power2Name": "Hook",
        "power2DescPrefix": "Free Action: ",
        "power2DescSuffix": "Move 1 enemy from a connected space to your space. Limit once per turn.",
        "collection": "Others",
    },
    {
        "faction": "alliance",
        "heroName": "Gryth Thurden",
        "heroTitle": "Gryphon Master",
        "heroQuote": "\"Speak with me when you're ready to go.\"",
        "heroImageUrl": "img/gryth-thurden.jpg",
        "heroImagePosition": "0px 0px",
        "heroImageSize": "cover",
        "health": 6,
        "startingLocation": "FROSTHOLD",
        "startingZone": "green",
        "power1Name": "Gryphon Ride",
        "power1DescPrefix": "",
        "power1DescSuffix": "Other heroes on your space can do a flight action to any space in the map.",
        "power2Name": "Flight Master",
        "power2DescPrefix": "",
        "power2DescSuffix": "Your flight actions are free."
    },
    {
        "faction": "hs",
        "heroName": "Gymer",
        "heroTitle": "King of Storm Giants",
        "heroQuote": "\"I will crush you all!\"",
        "heroImageUrl": "img/gymer.jpg",
        "heroImagePosition": "-3px -1px",
        "heroImageSize": "116%",
        "health": 8,
        "startingLocation": "Thrym's End",
        "startingZone": "purple",
        "power1Name": "Smash",
        "power1DescPrefix": "Action: ",
        "power1DescSuffix": "Remove up to 3 ghouls from your space.",
        "power2Name": "Throw",
        "power2DescPrefix": "Free Action: ",
        "power2DescSuffix": "Move 1 ghoul from your space to another space in your region. Limit once per turn.",
        "collection": "Northend Creatures",
    },
    {
        "faction": "alliance",
        "heroName": "Halford Wyrmbane",
        "heroTitle": "7th Legion High Commander",
        "heroQuote": "\"The first strike belongs to us.\"",
        "heroImageUrl": "img/halford-wyrmbane.jpg",
        "heroImagePosition": "0px 0px",
        "heroImageSize": "112%",
        "health": 7,
        "startingLocation": "NAXXRAMAS",
        "startingZone": "purple",
        "power1Name": "Crushing Leap",
        "power1DescPrefix": "Action: ",
        "power1DescSuffix": "Move to a connected space and remove 1 ghoul from that space. Limit once per turn.",
        "power2Name": "Rage",
        "power2DescPrefix": "",
        "power2DescSuffix": "+✊🏼 when you fight for every 2 enemies on your space.",
        "collection": "Others",
    },
    {
        "faction": "hs",
        "heroName": "Harrison Jones",
        "heroTitle": "Dr.",
        "heroQuote": "\"Stay behind me and you'll be fine.\"",
        "heroImageUrl": "img/harrison-jones.jpg",
        "heroImagePosition": "-180px -3px",
        "heroImageSize": "196%",
        "health": 6,
        "startingLocation": "GRIZZLEMAW",
        "startingZone": "purple",
        "power1Name": "Quick Escape",
        "power1DescPrefix": "Free Action: ",
        "power1DescSuffix": "After a quest action, move to a connected space. Limit once per turn.",
        "power2Name": "Archeologist\n",
        "power2DescPrefix": "",
        "power2DescSuffix": "At the start of your turn, flip the top card of the hero deck faceup; you may contribute it when you quest as if it were in your hand.",
        "collection": "Explorers & Hunters",
    },
    {
        "faction": "hs",
        "heroName": "Hemet Nesingwary",
        "heroTitle": "The Great Game Hunter",
        "heroQuote": "\"Eat lead!\"",
        "heroImageUrl": "img/hemet-nesingwary.jpg",
        "heroImagePosition": "-2px -17px",
        "heroImageSize": "100%",
        "health": 6,
        "startingLocation": "RIVER'S HEART",
        "startingZone": "red",
        "power1Name": "Big Game Hunter",
        "power1DescPrefix": "Action: ",
        "power1DescSuffix": "Remove 1 abomination from your space or a connected space. Limit once per turn.",
        "power2Name": "Explosive Trap",
        "power2DescPrefix": "Free Action: ",
        "power2DescSuffix": "Remove 1 ghoul from your space. Limit once per turn.",
        "collection": "Explorers & Hunters",
    },
    {
        "faction": "hs",
        "heroName": "Hodir",
        "heroTitle": "Father of Giants",
        "heroQuote": "\"Winds of the north consume you!\"",
        "heroImageUrl": "img/hodir.jpg",
        "heroImagePosition": "1px -65px",
        "heroImageSize": "100%",
        "health": 8,
        "startingLocation": "ULDUAR",
        "startingZone": "green",
        "power1Name": "Frost Fortitude",
        "power1DescPrefix": "",
        "power1DescSuffix": "+🛡️🛡️ when you fight.",
        "power2Name": "Protective Gaze",
        "power2DescPrefix": "",
        "power2DescSuffix": "Other heroes in your region have +🛡️ when they quest.",
        "collection": "Keepers of Ulduar",
    },
    {
        "faction": "scarlet",
        "heroName": "James Vishas",
        "heroTitle": "Interrogator of the Scarlet Crusade",
        "heroQuote": "\"Tell me... tell me everything!\"",
        "heroImageUrl": "img/james-vishas.jpg",
        "heroImagePosition": "0px 0px",
        "heroImageSize": "100%",
        "health": 6,
        "startingLocation": "ONSLAUGHT HARBOR",
        "startingZone": "red",
        "power1Name": "Naughty Secrets",
        "power1DescPrefix": "Free Action: ",
        "power1DescSuffix": "Remove 1 ghoul from your space. Limit once per turn.",
        "power2Name": "Shadow Word: Pain",
        "power2DescPrefix": "Free Action: ",
        "power2DescSuffix": "Remove 1 ghoul from a connected space. Limit once per turn.",
        "collection": "Scarlet Crusade",
    },
    {
        "faction": "kirin-tor",
        "heroName": "Jepetto Joybuzz",
        "heroTitle": "Toymaker",
        "heroQuote": "\"I'm a real toy now!\"",
        "heroImageUrl": "img/jepetto-joybuzz.jpg",
        "heroImagePosition": "0px -27px",
        "heroImageSize": "100%",
        "health": 7,
        "startingLocation": "DALARAN",
        "startingZone": "green",
        "power1Name": "Pretend",
        "power1DescPrefix": "",
        "power1DescSuffix": "When you contribute a hero card to a quest, the icon does not need to match the quest track.",
        "power2Name": "Titanium Seal of Dalaran",
        "power2DescPrefix": "Free Action: ",
        "power2DescSuffix": "Toss your luck!",
        "collection": "Kirin Tor",
    },
    {
        "faction": "wyrmrest",
        "heroName": "Kalecgos",
        "heroTitle": "Ambassador of the Blue Dragonflight",
        "heroQuote": "\"The fate of the world hangs in the balance.\"",
        "heroImageUrl": "img/kalecgos.png",
        "heroImagePosition": "-24px 0px",
        "heroImageSize": "156%",
        "health": 8,
        "startingLocation": "WYRMREST TEMPLE",
        "startingZone": "purple",
        "power1Name": "Blazing Shadows",
        "power1DescPrefix": "Action: ",
        "power1DescSuffix": "Move up to 2 spaces. Remove 1 ghoul from each space you exit. Limit once per turn.",
        "power2Name": "Kalecgos' Teleport",
        "power2DescPrefix": "Action: ",
        "power2DescSuffix": "Move another hero on your space to any space in your region. Limit once per turn.",
        "collection": "Wyrmrest Accord",
    },
    {
        "faction": "hs",
        "heroName": "Kilix",
        "heroTitle": "The Unraveler",
        "heroQuote": "\"This is no place for the meek.\"",
        "heroImageUrl": "img/kilix.jpg",
        "heroImagePosition": "1px -24px",
        "heroImageSize": "100%",
        "health": 6,
        "startingLocation": "AZJOL-NERUB",
        "startingZone": "red",
        "power1Name": "Web",
        "power1DescPrefix": "Free Action: ",
        "power1DescSuffix": "+🛡️ during your next fight action this turn. Limit once per turn.",
        "power2Name": "Azjol-anak Battleguards",
        "power2DescPrefix": "",
        "power2DescSuffix": "+✊🏼 and +🛡️ when you fight.",
        "collection": "Northend Creatures",
    },
    {
        "faction": "hs",
        "heroName": "King Mrgl-Mrgl",
        "heroTitle": "D.E.H.T.A.",
        "heroQuote": "\"I recently came here to observe the Winterfin murlocs.\"",
        "heroImageUrl": "img/king-mrgl-mrgl.jpg",
        "heroImagePosition": "1px -25px",
        "heroImageSize": "100%",
        "health": 6,
        "startingLocation": "RIVER'S HEART",
        "startingZone": "red",
        "power1Name": "Wrath",
        "power1DescPrefix": "Free Action: ",
        "power1DescSuffix": "Remove 1 ghoul from your space or a connected space. Limit once per turn.",
        "power2Name": "Rejuvenation",
        "power2DescPrefix": "Free Action: ",
        "power2DescSuffix": "1 hero on your space or a connected space heals 1. Limit once per turn.",
        "collection": "Others",
    },
    {
        "faction": "horde",
        "heroName": "Koltira Deathweaver",
        "heroTitle": "Knight of the Ebon Blade",
        "heroQuote": "\"Come and learn what it takes to slay an elf.\"",
        "heroImageUrl": "img/koltira-deathweaver.png",
        "heroImagePosition": "-18px 1px",
        "heroImageSize": "112%",
        "health": 7,
        "startingLocation": "AZJOL-NERUB",
        "startingZone": "red",
        "power1Name": "Byfrost",
        "power1DescPrefix": "",
        "power1DescSuffix": "After you fight, heal 1 for every 2 enemies killed.",
        "power2Name": "Bloodmist",
        "power2DescPrefix": "",
        "power2DescSuffix": 'Whenever you play a "Travel" card, you can move 1 additional space.',
        "collection": "Ebon Blade",
    },
    {
        "faction": "scarlet",
        "heroName": "Lilian Voss",
        "heroTitle": "Scarlet Crusader",
        "heroQuote": "\"Get away from me, you abomination!\"",
        "heroImageUrl": "img/lilian-voss-alive.jpg",
        "heroImagePosition": "-12px -69px",
        "heroImageSize": "104%",
        "health": 6,
        "startingLocation": "ONSLAUGHT HARBOR",
        "startingZone": "red",
        "power1Name": "Sprint",
        "power1DescPrefix": "Action: ",
        "power1DescSuffix": "Move up to 2 spaces. Limit once per turn.",
        "power2Name": "Stealth Skip",
        "power2DescPrefix": "Action: ",
        "power2DescSuffix": "While on a quest space, advance progress marker to the next space.",
        "collection": "Scarlet Crusade",
    },
    {
        "faction": "argent",
        "heroName": "Lilliandra",
        "heroTitle": "Archdruid of the Cenarion Circle",
        "heroQuote": "\"May Cenarius bless all those who defend Azeroth.\"",
        "heroImageUrl": "img/lilliandra.jpg",
        "heroImagePosition": "0px -35px",
        "heroImageSize": "cover",
        "health": 6,
        "startingLocation": "THE BREACH",
        "startingZone": "green",
        "power1Name": "Tranquility",
        "power1DescPrefix": "Action: ",
        "power1DescSuffix": "Each hero heals 1. Limit once per turn.",
        "power2Name": "Thorns Aura",
        "power2DescPrefix": "",
        "power2DescSuffix": "During fight actions on your space, treat all rolled 🛡️ as ✊🏼."
    },
    {
        "faction": "horde",
        "heroName": "Lor'themar Theron",
        "heroTitle": "Regent Lord of Quel'Thalas",
        "heroQuote": "\"The blood elves will endure any hardship.\"",
        "heroImageUrl": "img/lorthemar-theron.jpg",
        "heroImagePosition": "-76px -24px",
        "heroImageSize": "176%",
        "health": 7,
        "startingLocation": "DALARAN",
        "startingZone": "green",
        "power1Name": "Cleave",
        "power1DescPrefix": "Action: ",
        "power1DescSuffix": "Remove exactly 1 enemy from your space and up to 1 ghoul from a connected space. Limit once per turn.",
        "power2Name": "Mass Charm",
        "power2DescPrefix": "",
        "power2DescSuffix": "Abominations always follow you during the 'Activate Abominations' step.",
        "collection": "Mainland Reinforcements",
    },
    {
        "faction": "hs",
        "heroName": "Lurielle",
        "heroTitle": "Frost nymph",
        "heroQuote": "\"My sisters and I welcome you.\"",
        "heroImageUrl": "img/frost-nymph.jpg",
        "heroImagePosition": "-2px -43px",
        "heroImageSize": "100%",
        "health": 6,
        "startingLocation": "UTGARDE KEEP",
        "startingZone": "purple",
        "power1Name": "Frost Shock",
        "power1DescPrefix": "Free Action: ",
        "power1DescSuffix": "Remove 1 ghoul from your space. Limit once per turn.",
        "power2Name": "Four-legged",
        "power2DescPrefix": "",
        "power2DescSuffix": "During move actions, you may move up to 2 spaces.",
        "collection": "Northend Creatures",
    },
    {
        "faction": "alliance",
        "heroName": "Magni Bronzebeard",
        "heroTitle": "Lord of Ironforge",
        "heroQuote": "\"Feel the fury of the mountain!\"",
        "heroImageUrl": "img/magni.jpg",
        "heroImagePosition": "-4px -10px",
        "heroImageSize": "100%",
        "health": 7,
        "startingLocation": "FROSTHOLD",
        "startingZone": "green",
        "power1Name": "Avatar",
        "power1DescPrefix": "Action: ",
        "power1DescSuffix": "+🛡️ when you fight or quest this turn. Limit once per turn.",
        "power2Name": "Thunderous Charge",
        "power2DescPrefix": "Action: ",
        "power2DescSuffix": "Move to a connected space and remove up to 2 ghouls from that space. Limit once per turn.",
        "collection": "Mainland Reinforcements",
    },
    {
        "faction": "argent",
        "heroName": "Mariel Trueheart",
        "heroTitle": "Seneschal of the Argent Tournament",
        "heroQuote": "\"Our strength is bolstered with you fighting by our side.\"",
        "heroImageUrl": "img/mariel-trueheart.png",
        "heroImagePosition": "-1px -41px",
        "heroImageSize": "100%",
        "health": 7,
        "startingLocation": "ARGENT TOURNAMENT",
        "startingZone": "green",
        "power1Name": "Charge",
        "power1DescPrefix": "Action: ",
        "power1DescSuffix": "Move to a connected space, roll 1 die and remove 1 ghoul per rolled ✊🏼. Limit once per turn.",
        "power2Name": "Joust",
        "power2DescPrefix": "Action: ",
        "power2DescSuffix": "Each hero rolls 2 dice, each of the highest ✊🏼 rollers draw 1 card from the top of the hero discard. Limit once per turn."
    },
    {
        "faction": "hs",
        "heroName": "Mimiron",
        "heroTitle": "The Grand Architect",
        "heroQuote": "\"Time for some science!\"",
        "heroImageUrl": "img/mimiron.png",
        "heroImagePosition": "0px -27px",
        "heroImageSize": "100%",
        "health": 7,
        "startingLocation": "ULDUAR",
        "startingZone": "green",
        "power1Name": "Self Repair",
        "power1DescPrefix": "Free Action: ",
        "power1DescSuffix": "Discard 1 hero card and heal to full health. Limit once per turn.",
        "power2Name": "Destabilization Matrix",
        "power2DescPrefix": "",
        "power2DescSuffix": "Heroes on your space and connected spaces have +🛡️ when they fight.",
        "collection": "Keepers of Ulduar",
    },
    {
        "faction": "wyrmrest",
        "heroName": "Nalice",
        "heroTitle": "Ambassador of the Black Dragonflight",
        "heroQuote": "\"The presence of a Black Dragon makes you nervous?",
        "heroImageUrl": "img/nalice.jpg",
        "heroImagePosition": "-58px 1px",
        "heroImageSize": "140%",
        "health": 8,
        "startingLocation": "WYRMREST TEMPLE",
        "startingZone": "purple",
        "power1Name": "Breathe",
        "power1DescPrefix": "Action: ",
        "power1DescSuffix": "Remove 1 ghoul from your space and 1 ghoul from a connected space. Limit once per turn.",
        "power2Name": "Fly",
        "power2DescPrefix": "Action: ",
        "power2DescSuffix": "Move up to 3 spaces. Limit once per turn.",
        "collection": "Wyrmrest Accord",
    },
    {
        "faction": "horde",
        "heroName": "Nathanos Blightcaller",
        "heroTitle": "Champion of the Banshee Queen",
        "heroQuote": "\"Good boy! Now put it back on the bone pile.\"",
        "heroImageUrl": "img/nathanos-blightcaller.jpg",
        "heroImagePosition": "0px 0px",
        "heroImageSize": "124%",
        "health": 7,
        "startingLocation": "VENGEANCE LANDING",
        "startingZone": "purple",
        "power1Name": "Psychic Scream",
        "power1DescPrefix": "Free Action: ",
        "power1DescSuffix": "Move 1 ghoul from a connected space to another space connected to it. Limit once per turn.",
        "power2Name": "Blighthounds",
        "power2DescPrefix": "",
        "power2DescSuffix": "+✊🏼 when you fight.",
        "collection": "Mainland Reinforcements",
    },
    {
        "faction": "horde",
        "heroName": "Nazgrim",
        "heroTitle": "Sergeant",
        "heroQuote": "\"I hope you have the courage to die bravely.\"",
        "heroImageUrl": "img/nazgrim.jpg",
        "heroImagePosition": "0px 0px",
        "heroImageSize": "cover",
        "health": 6,
        "startingLocation": "AMBERPINE LODGE",
        "startingZone": "purple",
        "power1Name": "Kor'kron Banner",
        "power1DescPrefix": "",
        "power1DescSuffix": "Horde heroes on your space and connected spaces have +✊🏼 when they fight.",
        "power2Name": "War Song",
        "power2DescPrefix": "",
        "power2DescSuffix": "Horde heroes on your space and connected spaces have +🛡️ when they fight.",
        "collection": "Others",
    },
    {
        "faction": "hs",
        "heroName": "Oacha'noa",
        "heroTitle": "Goddess of the Depths",
        "heroQuote": "\"Why do you call me forth?\"",
        "heroImageUrl": "img/oachanoa.jpg",
        "heroImagePosition": "0px 0px",
        "heroImageSize": "124%",
        "health": 8,
        "startingLocation": "VENGEANCE LANDING",
        "startingZone": "purple",
        "power1Name": "Deep Sea Dweller",
        "power1DescPrefix": "",
        "power1DescSuffix": "You can only be at Onslaught Harbor, Vengeance Landing, or Argent Tournament, and can move directly between them as one action.",
        "power2Name": "Compulsion",
        "power2DescPrefix": "",
        "power2DescSuffix": "Heroes in your region have +✊🏼 during their actions.",
        "collection": "Northend Creatures",
    },
    {
        "faction": "horde",
        "heroName": "Putress",
        "heroTitle": "Grand Apothecary",
        "heroQuote": "\"Did you think we had forgotten?\"",
        "heroImageUrl": 'img/putress.jpg',
        "heroImagePosition": "0px -4px",
        "heroImageSize": "100%",
        "health": 6,
        "startingLocation": "THE WRATHGATE",
        "startingZone": "red",
        "power1Name": "New Plague",
        "power1DescPrefix": "Action: ",
        "power1DescSuffix": "Deal up to 3 damage on a connected space. All heroes on that space die. Limit once per turn.",
        "power2Name": "Coup Plotter",
        "power2DescPrefix": "",
        "power2DescSuffix": "You cannot use hero card effects on other heroes.",
        "collection": "The Wrathgate",
    },
    {
        "faction": "kirin-tor",
        "heroName": "Rhonin",
        "heroTitle": "Leader of the Kirin Tor",
        "heroQuote": "\"Citizens of Dalaran!\"",
        "heroImageUrl": "img/rhonin.png",
        "heroImagePosition": "-10px -4px",
        "heroImageSize": "104%",
        "health": 6,
        "startingLocation": "DALARAN",
        "startingZone": "green",
        "power1Name": "Arcane Explosion",
        "power1DescPrefix": "Action: ",
        "power1DescSuffix": "Remove up to 2 ghouls among your space and connected spaces. Limit once per turn.",
        "power2Name": "Dalaran Summon",
        "power2DescPrefix": "Action: ",
        "power2DescSuffix": "Move a hero in your region to Dalaran. Limit once per turn.",
        "collection": "Kirin Tor",
    },
    {
        "faction": "hs",
        "heroName": "Rimblat Earthshatter",
        "heroTitle": "The Earthen Ring",
        "heroQuote": "\"The elements cry out that this land is almost dead.\"",
        "heroImageUrl": "img/rimblat-earthshatter.jpg",
        "heroImagePosition": "2px -94px",
        "heroImageSize": "100%",
        "health": 7,
        "startingLocation": "KOLRAMAS",
        "startingZone": "purple",
        "power1Name": "Chain Heal",
        "power1DescPrefix": "Action: ",
        "power1DescSuffix": "Choose up to 3 heroes in connected spaces including yours. For each, roll 1 die and heal that hero 1 per rolled ✊🏼.",
        "power2Name": "Thunder",
        "power2DescPrefix": "Action: ",
        "power2DescSuffix": "Remove up to 2 ghouls from a space in your region. Limit once per turn.",
        "collection": "Others",
    },
    {
        "faction": "horde",
        "heroName": "Roanauk Icemist",
        "heroTitle": "High Chieftain of the Taunka",
        "heroQuote": "\"For my Taunka brothers and sisters!\"",
        "heroImageUrl": "img/roanauk-icemist.jpg",
        "heroImagePosition": "1px 0px",
        "heroImageSize": "116%",
        "health": 7,
        "startingLocation": "AZJOL-NERUB",
        "startingZone": "red",
        "power1Name": "Icemist's Blessing",
        "power1DescPrefix": "Action: ",
        "power1DescSuffix": "+✊🏼✊🏼 during your next fight action this turn. Limit once per turn.",
        "power2Name": "Acclimatized to Cold",
        "power2DescPrefix": "",
        "power2DescSuffix": "+✊🏼 when you rest.",
        "collection": "Northend Creatures",
    },
    {
        "faction": "horde",
        "heroName": "Rokhan",
        "heroTitle": "Scout",
        "heroQuote": "\"Death be a real trip man!\"",
        "heroImageUrl": "img/rokhan.jpg",
        "heroImagePosition": "0px 0px",
        "heroImageSize": "112%",
        "health": 7,
        "startingLocation": "THE WRATHGATE",
        "startingZone": "red",
        "power1Name": "Serpent Totem",
        "power1DescPrefix": "Free Action: ",
        "power1DescSuffix": "Roll 1 die and remove 1 ghoul per rolled ✊🏼 from your space. Limit once per turn.",
        "power2Name": "Sinkhole Totem",
        "power2DescPrefix": "Free Action: ",
        "power2DescSuffix": "Choose a connected space, roll 1 die and remove 1 ghoul per rolled ✊🏼 and 🛡️. Limit once per turn."
    },
    {
        "faction": "horde",
        "heroName": "Rommath",
        "heroTitle": "Grand Magister",
        "heroQuote": "\"Impossible is only what we allow it to be.\"",
        "heroImageUrl": "img/rommath.jpg",
        "heroImagePosition": "2px -22px",
        "heroImageSize": "cover",
        "health": 7,
        "startingLocation": "DALARAN",
        "startingZone": "green",
        "power1Name": "Flamestrike",
        "power1DescPrefix": "Action: ",
        "power1DescSuffix": "Remove up to 2 ghouls from a connected space. Limit once per turn.",
        "power2Name": "Molten Armor",
        "power2DescPrefix": "",
        "power2DescSuffix": "Remove 1 ghoul from your space after you suffer damage.",
        "collection": "Mainland Reinforcements",
    },
    {
        "faction": "scarlet",
        "heroName": "Sally Whitemane",
        "heroTitle": "High Inquisitor of the Scarlet Crusade",
        "heroQuote": "\"The light has spoken!\"",
        "heroImageUrl": "img/sally-whitemane.jpg",
        "heroImagePosition": "-11px -35px",
        "heroImageSize": "104%",
        "health": 6,
        "startingLocation": "ONSLAUGHT HARBOR",
        "startingZone": "red",
        "power1Name": "Divine Reckoning",
        "power1DescPrefix": "Action: ",
        "power1DescSuffix": "Fight and heal 1 hero on your space 1 for each rolled 🛡️. Limit once per turn.",
        "power2Name": "Searing Lash",
        "power2DescPrefix": "Free Action: ",
        "power2DescSuffix": "Remove 1 ghoul from your space and move up to 1 ghoul to a connected space. Limit once per turn.",
        "collection": "Scarlet Crusade",
    },
    {
        "faction": "alliance",
        "heroName": "Shandris Feathermoon",
        "heroTitle": "General of the Sentinel Army",
        "heroQuote": "\"The thrill of the hunt... There's nothing like it.\"",
        "heroImageUrl": "img/shandris-feathermoon.jpg",
        "heroImagePosition": "0px -21px",
        "heroImageSize": "100%",
        "health": 7,
        "startingLocation": "GRIZZLEMAW",
        "startingZone": "purple",
        "power1Name": "Penetrating Shot",
        "power1DescPrefix": "Action: ",
        "power1DescSuffix": "Remove 1 ghoul from your space and 1 ghoul from a connected space. Limit once per turn.",
        "power2Name": "Smoke Bomb",
        "power2DescPrefix": "Action: ",
        "power2DescSuffix": "Heroes in your space may move to a connected space. Limit once per turn.",
        "collection": "Mainland Reinforcements",
    },
    {
        "faction": "argent",
        "heroName": "Sister Colleen Tulley",
        "heroTitle": "Food & Drink",
        "heroQuote": "\"Light be with you.\"",
        "heroImageUrl": "img/sister-colleen-tulley.jpg",
        "heroImagePosition": "-25px -37px",
        "heroImageSize": "132%",
        "health": 6,
        "startingLocation": "THE BREACH",
        "startingZone": "green",
        "power1Name": "Chicken Soup",
        "power1DescPrefix": "Action: ",
        "power1DescSuffix": "A hero on your space rests with +1.",
        "power2Name": "Flash heal",
        "power2DescPrefix": "Free Action: ",
        "power2DescSuffix": "A hero on your space heals 2. Limit once per turn.",
        "collection": "Argent Crusade",
    },
    {
        "faction": "argent",
        "heroName": "Spitzpatrick",
        "heroTitle": "Crusade Engineer",
        "heroQuote": "\"I have work to attend!\"",
        "heroImageUrl": "img/spitzpatrick.jpg",
        "heroImagePosition": "0px 0px",
        "heroImageSize": "cover",
        "health": 7,
        "startingLocation": "THE BREACH",
        "startingZone": "green",
        "power1Name": "Boom Tech",
        "power1DescPrefix": "Free Action: ",
        "power1DescSuffix": "Discard 1 card and deal 4 damage on your space. Limit once per turn.",
        "power2Name": "Mind Control Tech",
        "power2DescPrefix": "Free Action: ",
        "power2DescSuffix": "Discard 1 card and remove 1 ghoul from each connected space with an abomination.  Limit once per turn.",
        "collection": "Argent Crusade",
    },
    {
        "faction": "alliance",
        "heroName": "Thassarian",
        "heroTitle": "Knight of the Ebon Blade",
        "heroQuote": "\"Sometimes lessons are painful, aren't they?\"",
        "heroImageUrl": "img/thassarian.jpg",
        "heroImagePosition": "0px -18px",
        "heroImageSize": "100%",
        "health": 7,
        "startingLocation": "VALIANCE KEEP",
        "startingZone": "red",
        "power1Name": "Skybreaker Ride",
        "power1DescPrefix": "Action: ",
        "power1DescSuffix": "When on a space connected to Icecrown Citadel, move directly to another space also connected to Icecrown Citadel.",
        "power2Name": "Frost Presence",
        "power2DescPrefix": "",
        "power2DescSuffix": "+🛡️ when you quest.",
        "collection": "Ebon Blade",
    },
    {
        "faction": "hs",
        "heroName": "Thorim",
        "heroTitle": "Stormlord",
        "heroQuote": "\"You call down the vengeance of THUNDER!\"",
        "heroImageUrl": "img/thorim.jpg",
        "heroImagePosition": "0px 0px",
        "heroImageSize": "100%",
        "health": 8,
        "startingLocation": "TEMPLE OF STORMS",
        "startingZone": "green",
        "power1Name": "Krolmir's Fury",
        "power1DescPrefix": "Action: ",
        "power1DescSuffix": "Roll 2 dice, and remove 1 ghoul for each rolled ✊🏼 among your space and a connected space. Limit once per turn.",
        "power2Name": "Titanic Storm",
        "power2DescPrefix": "",
        "power2DescSuffix": "Heroes in your region have +✊🏼 when they fight.",
        "collection": "Keepers of Ulduar",
    },
    {
        "faction": "kirin-tor",
        "heroName": "Timothy Jones",
        "heroTitle": "Grand Master Jewelcrafting Trainer",
        "heroQuote": "\"As The Light as my witness, jewels are my business!\"",
        "heroImageUrl": "img/timothy-jones.jpg",
        "heroImagePosition": "0px -28px",
        "heroImageSize": "100%",
        "health": 6,
        "startingLocation": "DALARAN",
        "startingZone": "green",
        "power1Name": "Jeweler",
        "power1DescPrefix": "",
        "power1DescSuffix": "All heroes in your region have +🛡️ when they fight or quest.",
        "power2Name": "Civilian",
        "power2DescPrefix": "",
        "power2DescSuffix": "Cancel 1 rolled ✊🏼 when you fight.",
        "collection": "Kirin Tor",
        "shortName": "Armorer",
    },
    {
        "faction": "alliance",
        "heroName": "Valeera Sanguinar",
        "heroTitle": "Champion of the Crimson Ring",
        "heroQuote": "\"Respect my people, or pay the price!\"",
        "heroImageUrl": "img/valeera-sanguinar.png",
        "heroImagePosition": "0px -9px",
        "heroImageSize": "104%",
        "health": 6,
        "startingLocation": "VALIANCE KEEP",
        "startingZone": "red",
        "power1Name": "Eviscerate",
        "power1DescPrefix": "Action: ",
        "power1DescSuffix": "Remove 1 abomination from your space. Limit once per turn.",
        "power2Name": "Poisoned Blades",
        "power2DescPrefix": "",
        "power2DescSuffix": "+✊🏼 when you fight.",
        "collection": "Mainland Reinforcements",
    },
    {
        "faction": "horde",
        "heroName": "Varok Saurfang",
        "heroTitle": "High Overlord",
        "heroQuote": "\"No matter how dire the battle, never forsake it.\"",
        "heroImageUrl": "img/varok-saurfang.jpg",
        "heroImagePosition": "1px -41px",
        "heroImageSize": "100%",
        "health": 7,
        "startingLocation": "WARSONG HOLD",
        "startingZone": "red",
        "power1Name": "Whirlwind",
        "power1DescPrefix": "Action: ",
        "power1DescSuffix": "Deal up to 3 damage on your space. Limit once per turn.",
        "power2Name": "Terrifying Roar",
        "power2DescPrefix": "Free Action: ",
        "power2DescSuffix": "Move 1 ghoul from your space to a connected space. Limit once per turn.",
        "collection": "Others",
    },
    {
        "faction": "alliance",
        "heroName": "Velen",
        "heroTitle": "Prophet",
        "heroQuote": "\"Salvation, young one. It waits for us all.\"",
        "heroImageUrl": "img/velen.jpg",
        "heroImagePosition": "-51px -5px",
        "heroImageSize": "132%",
        "health": 7,
        "startingLocation": "VALIANCE KEEP",
        "startingZone": "red",
        "power1Name": "Holy Nova",
        "power1DescPrefix": "Action: ",
        "power1DescSuffix": "Deal 1 damage on your space and each connected space. Limit once per turn.",
        "power2Name": "Prayer of Healing",
        "power2DescPrefix": "Action: ",
        "power2DescSuffix": "Each hero on your space and connected spaces heals 1. Limit once per turn.",
        "collection": "Mainland Reinforcements",
    },
    {
        "faction": "horde",
        "heroName": "Velonara",
        "heroTitle": "Dark Ranger",
        "heroQuote": "\"I'll even get you started.\"",
        "heroImageUrl": "img/velonara.jpg",
        "heroImagePosition": "0px 0px",
        "heroImageSize": "100%",
        "health": 6,
        "startingLocation": "VENGEANCE LANDING",
        "startingZone": "purple",
        "power1Name": "Life Drain",
        "power1DescPrefix": "Action: ",
        "power1DescSuffix": "Remove 1 abomination from your space and heal 3. Limit once per turn.",
        "power2Name": "Black Arrow",
        "power2DescPrefix": "",
        "power2DescSuffix": 'During your own actions, when you play a "Fight" or "Defend" card, remove 1 ghoul from your space.',
        "collection": "Mainland Reinforcements",
    },
    {
        "faction": "alliance",
        "heroName": "Vereesa Windrunner",
        "heroTitle": "Ranger-General of the Silver Covenant",
        "heroQuote": "\"We have all lost so much.\"",
        "heroImageUrl": "img/vereesa-windrunner.jpg",
        "heroImagePosition": "-1px -68px",
        "heroImageSize": "100%",
        "health": 6,
        "startingLocation": "DALARAN",
        "startingZone": "green",
        "power1Name": "Multi-Shot",
        "power1DescPrefix": "Action: ",
        "power1DescSuffix": "Deal up to 3 damage among your space and connected spaces. Limit once per turn.",
        "power2Name": "Track",
        "power2DescPrefix": "",
        "power2DescSuffix": "At the start of your turn, flip the top card of the hero deck faceup.",
        "collection": "Kirin Tor",
    },
    {
        "faction": "alliance",
        "heroName": "Vindicator Maraad",
        "heroTitle": "Hammer of the Light",
        "heroQuote": "\"The Light may have infinite patience, but I do not.\"",
        "heroImageUrl": "img/vindicator-maraad.jpg",
        "heroImagePosition": "-4px -26px",
        "heroImageSize": "100%",
        "health": 6,
        "startingLocation": "THE BREACH",
        "startingZone": "green",
        "power1Name": "Divine Storm",
        "power1DescPrefix": "Action: ",
        "power1DescSuffix": "Discard 1 'Fight' card and remove up to 4 ghouls among yours and connected spaces. Limit once per turn.",
        "power2Name": "Hammer of the Naaru",
        "power2DescPrefix": "",
        "power2DescSuffix": "+✊🏼✊🏼 when you fight and there's an abomination on your space.",
        "collection": "Others",
    }
]

const collections = heroConfigs.reduce((result, hero) => {
    const collectionIndex = result.findIndex(group => group.name === hero.collection);
    if (collectionIndex !== -1) {
        result[collectionIndex].heroes.push(hero.heroName);
    } else {
        result.push({ name: hero.collection, heroes: [hero.heroName] });
    }
    return result;
}, []);